server:
  port: ${PORT:8085}

spring:
  application:
    name: payment-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/paymentdb}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    stream:
      bindings:
        payment-events-out-0:
          destination: payment-events
          content-type: application/json

stripe:
  api-key: ${STRIPE_API_KEY:sk_test_}

eureka:
  client:
    enabled: ${ENABLE_EUREKA:false}
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka}
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:payment-service}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.projects: DEBUG
    org.hibernate.SQL: DEBUG
